name: "Build poetry project"
description: "Build any python project using poetry"

inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.11"
  poetry-version:
    description: "Poetry version"
    required: true
    default: 1.2.2

runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: ${{ inputs.poetry-version }}

      - name: Install dependencies using Poetry
        shell: bash
        run: poetry config virtualenvs.create false && poetry install
